language: node_js
node_js:
  - '12'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm install -g yarn
  - npm config set spin false
  - npm install -g npm@^6.9.0
script:
  - yarn test-ci
  - yarn build
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "gO2h/BToSqWVENYkLTH4i0r7IjHoGZx3xaEjCmmSOsfDdWhjK3u6pqziPs3gKIIKPZiQHWwKW1eCRoR4ZBDatICzLf44JV4sAIjJi7jT3IDkpBLqAgmBiIRyr/6aQrQPZUDgeI2ptZLSnPGW3o2NbUsWs6JdzNws2vpo5qdB+yE5WgOHwQJZN1u0ARe6x1dtykFCPw9Ld+04pxgHjVqKRDd554dsPQYh0uKz9SzD76+8+TAj7D4Yes4HZCTGxmpAH2TZ7MjRHGzVFIkJVyUx4fDcFnNpFsXLzD0eabqhG2wUvkhjLGpmP/CmyuUT3PPKdo6JjjYJQc2DpgZNeVLZgeUOwgyLH5G/NVdiv2ko/nbLzjxYjQqFVJXGGZ2ogfdEw4oJvT3coFdXdNVcvODv+nr0J8Ra67SWJ7O5FwZtrzpzAoVIwG39KM3NERW3EHhwQuQfQkQ9bHj2Oc5rB/2BLV8h6VQEUFNv6AU/nWVOs1NmL/jM+9hlq8P5m0pMu0w2hMn8zd9dqDgoRVqs1me82vvxCeC2C8dchPHXr7LvK7N7zhGlmho6Id4ysbLzf0vYpniDxeE9ec6widQy5EAYpVJgZAwWulZ14KOgMIy+Pb0BvqVsXdYfNZTOJ7BnnI619vVB7APe62KgZlbOdjgHRYgTwaDm3BPRZSGX69gyCJE="
  file:
    - build/_output/template-widget.wigt
    - build/_output/template-widget-build-info.yml
  on:
    tags: true
    repo: ucfopen/materia-template-widget
notifications:
  email: false
  slack:
    secure: "loyq/iyyu0BBUXxpr9e+T+C3blXRqQLgtnnmRB0ntwH6g1F3yqFaaK6oei8Doo2QI9EaeoZRCDnmEY2vzoBrYyFLZK8lpoWSrnm7fG3AHjCnqecMETdTSa8ZVmVPbYieUCCqb2BDR39927YgPF/J8Es0TjYHNHAxg5X2PXmcfWQI6ZVmmti6b2V4ZvMW6xaMoNYFxk1lnUKZ48uGbASLmCwjGrfrn3cGzFM348eVFHrKB7JwB222zstbMSeHV+BLJTn48AxSEq7EUC8QjiZ8tI08i96EBBESrNszfC22Dl1XcdHw6dLp+BFUubIGeazItMYQ78bTtA/OR5kajsGFiIpKBimWHs/+Y5lvIQqTuJjAKFII6QIpc8B8qqJtEE+32hlbqfE2kf/ygI/yVp5XVHkcY7jp5036gcbUnLdhiVxN6KG3LRTz1wXqfk//ftOWczOOvuLxWdoYwwUvJVdd6rSbmDEQHkPoqUGqiinFPVavdEe+VFmwNySKUg+N3TQpV9SB45zo/KKcWv6rAiV6fiimrbmh0YtibRYklmLhHBs7tuVkph7P0vCS5E76PWitPR1AWx+6NRQg4RCk16N2XU7GQYO3IdoatqG22eSB0F4KR3mEGdWPTEXj6LDj6hcHkt0KEhrLvNPIJvXFj9/F/lczBxrA6Id1/6GT8sPhlis="
